//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace picsonaplane.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("picsonaplane.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] A4_measurements {
            get {
                object obj = ResourceManager.GetObject("A4_measurements", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///	&lt;/body&gt;
        ///&lt;/html&gt;
        ///
        ///&lt;!--END OF FILE--&gt;
        ///.
        /// </summary>
        internal static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--WOLFPAW Pics on a Plane HTML output template--&gt;
        ///&lt;!--Generated by Pics on a Plane - WolfPaw Studios - &lt;DATE&gt; &lt;TIME&gt;--&gt;
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;POAP - HTML output&lt;/title&gt;
        ///		&lt;meta charset=&quot;UTF-8&quot;; /&gt;
        ///		
        ///		&lt;style&gt;
        ///			body{ background:&lt;BODYBG&gt;; padding: 0px; margin: 0px; float: clear; }
        ///			
        ///			img{ position: relative; display:block;  margin-left: auto; margin-right: auto; }
        ///			
        ///			div{ position:relative; display:block; width:1200 px; height:900 px; margin:50px; }
        ///
        ///			.fullwid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!--POAP PAGE: &lt;PAGEID&gt; TYPE: 133--&gt;
        ///&lt;!--START PAGE--&gt;
        ///
        ///	&lt;div class=&apos;poap_133&apos; id=&apos;&lt;PAGEID&gt;&apos;&gt;
        ///		
        ///		&lt;span class=&apos;pagerow&apos;&gt; 
        ///			&lt;div class=&apos;picdiv_1&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_1&apos; class=&apos;&lt;WIDHEI&gt; pic_1&apos; data-posRow=&apos;1&apos; data-posCol=&apos;1&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; onclick=&apos;pic_click(event);&apos; /&gt;&lt;/div&gt;
        ///		&lt;/span&gt;
        ///		
        ///		&lt;span class=&apos;pagerow&apos;&gt; 
        ///			&lt;div class=&apos;picdiv_3&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_2_1&apos; class=&apos;&lt;WIDHEI&gt; pic_3&apos; data-posRow=&apos;2&apos; data-posCol=&apos;1&apos; name=&apos;&lt;PICNAME [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poap_133 {
            get {
                return ResourceManager.GetString("poap_133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!--POAP PAGE: &lt;PAGEID&gt; TYPE: 134--&gt;
        ///&lt;!--START PAGE--&gt;
        ///
        ///	&lt;div class=&apos;poap_134&apos; id=&apos;&lt;PAGEID&gt;&apos;&gt;
        ///		
        ///		&lt;span class=&apos;pagerow&apos;&gt; 
        ///			&lt;div class=&apos;picdiv_1&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_1&apos; class=&apos;&lt;WIDHEI&gt; pic_1&apos; data-posRow=&apos;1&apos; data-posCol=&apos;1&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; onclick=&apos;pic_click(event);&apos; /&gt;&lt;/div&gt;
        ///		&lt;/span&gt;
        ///		
        ///		&lt;span class=&apos;pagerow&apos;&gt; 
        ///			&lt;div class=&apos;picdiv_3&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_2_1&apos; class=&apos;&lt;WIDHEI&gt; pic_3&apos; data-posRow=&apos;2&apos; data-posCol=&apos;1&apos; name=&apos;&lt;PICNAME [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poap_134 {
            get {
                return ResourceManager.GetString("poap_134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!--POAP PAGE: &lt;PAGEID&gt; TYPE: 212--&gt;
        ///&lt;!--START PAGE--&gt;
        ///
        ///	&lt;div class=&apos;poap_212&apos; id=&apos;&lt;PAGEID&gt;&apos;&gt;
        ///		
        ///		&lt;span class=&apos;pagerow&apos;&gt; 
        ///			&lt;div class=&apos;picdiv_2&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_1&apos; class=&apos;&lt;WIDHEI&gt; pic_2&apos; data-posRow=&apos;1&apos; data-posCol=&apos;1&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; onclick=&apos;pic_click(event);&apos; /&gt;&lt;/div&gt;
        ///			&lt;div class=&apos;picdiv_2&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_2&apos; class=&apos;&lt;WIDHEI&gt; pic_2&apos; data-posRow=&apos;1&apos; data-posCol=&apos;2&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; oncli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poap_212 {
            get {
                return ResourceManager.GetString("poap_212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!--POAP PAGE: &lt;PAGEID&gt; TYPE: 232--&gt;
        ///&lt;!--START PAGE--&gt;
        ///
        ///	&lt;div class=&apos;poap_232&apos; id=&apos;&lt;PAGEID&gt;&apos;&gt;
        ///		
        ///		&lt;span class=&apos;pagerow&apos;&gt; 
        ///			&lt;div class=&apos;picdiv_2&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_1&apos; class=&apos;&lt;WIDHEI&gt; pic_2&apos; data-posRow=&apos;1&apos; data-posCol=&apos;1&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; onclick=&apos;pic_click(event);&apos; /&gt;&lt;/div&gt;
        ///			&lt;div class=&apos;picdiv_2&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_2&apos; class=&apos;&lt;WIDHEI&gt; pic_2&apos; data-posRow=&apos;1&apos; data-posCol=&apos;2&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; oncli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poap_232 {
            get {
                return ResourceManager.GetString("poap_232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!--POAP PAGE: &lt;PAGEID&gt; TYPE: 313--&gt;
        ///&lt;!--START PAGE--&gt;
        ///
        ///	&lt;div class=&apos;poap_313&apos; id=&apos;&lt;PAGEID&gt;&apos;&gt;
        ///		
        ///		&lt;span class=&apos;pagerow&apos;&gt; 
        ///			&lt;div class=&apos;picdiv_3&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_1&apos; class=&apos;&lt;WIDHEI&gt; pic_3&apos; data-posRow=&apos;1&apos; data-posCol=&apos;1&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; onclick=&apos;pic_click(event);&apos; /&gt;&lt;/div&gt;
        ///			&lt;div class=&apos;picdiv_3&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_2&apos; class=&apos;&lt;WIDHEI&gt; pic_3&apos; data-posRow=&apos;1&apos; data-posCol=&apos;2&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; oncli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poap_313 {
            get {
                return ResourceManager.GetString("poap_313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!--POAP PAGE: &lt;PAGEID&gt; TYPE: 323--&gt;
        ///&lt;!--START PAGE--&gt;
        ///
        ///	&lt;div class=&apos;poap_323&apos; id=&apos;&lt;PAGEID&gt;&apos;&gt;
        ///		
        ///		&lt;span class=&apos;pagerow&apos;&gt; 
        ///			&lt;div class=&apos;picdiv_3&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_1&apos; class=&apos;&lt;WIDHEI&gt; pic_3&apos; data-posRow=&apos;1&apos; data-posCol=&apos;1&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; onclick=&apos;pic_click(event);&apos; /&gt;&lt;/div&gt;
        ///			&lt;div class=&apos;picdiv_3&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_2&apos; class=&apos;&lt;WIDHEI&gt; pic_3&apos; data-posRow=&apos;1&apos; data-posCol=&apos;2&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; oncli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poap_323 {
            get {
                return ResourceManager.GetString("poap_323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!--POAP PAGE: &lt;PAGEID&gt; TYPE: 333--&gt;
        ///&lt;!--START PAGE--&gt;
        ///
        ///	&lt;div class=&apos;poap_333&apos; id=&apos;&lt;PAGEID&gt;&apos;&gt;
        ///		
        ///		&lt;span class=&apos;pagerow&apos;&gt; 
        ///			&lt;div class=&apos;picdiv_3&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_1&apos; class=&apos;&lt;WIDHEI&gt; pic_3&apos; data-posRow=&apos;1&apos; data-posCol=&apos;1&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; onclick=&apos;pic_click(event);&apos; /&gt;&lt;/div&gt;
        ///			&lt;div class=&apos;picdiv_3&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_2&apos; class=&apos;&lt;WIDHEI&gt; pic_3&apos; data-posRow=&apos;1&apos; data-posCol=&apos;2&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; oncli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poap_333 {
            get {
                return ResourceManager.GetString("poap_333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!--POAP PAGE: &lt;PAGEID&gt; TYPE: 434--&gt;
        ///&lt;!--START PAGE--&gt;
        ///
        ///	&lt;div class=&apos;poap_434&apos; id=&apos;&lt;PAGEID&gt;&apos;&gt;
        ///		
        ///		&lt;span class=&apos;pagerow&apos;&gt; 
        ///			&lt;div class=&apos;picdiv_4&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_1&apos; class=&apos;&lt;WIDHEI&gt; pic_4&apos; data-posRow=&apos;1&apos; data-posCol=&apos;1&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; onclick=&apos;pic_click(event);&apos; /&gt;&lt;/div&gt;
        ///			&lt;div class=&apos;picdiv_4&apos;&gt;&lt;img src=&apos;&lt;PICSRC&gt;&apos; id=&apos;&lt;PAGEID&gt;_1_2&apos; class=&apos;&lt;WIDHEI&gt; pic_4&apos; data-posRow=&apos;1&apos; data-posCol=&apos;2&apos; name=&apos;&lt;PICNAME&gt;&apos; alt=&apos;&lt;PICNAME&gt;&apos; title=&apos;&lt;PICNAME&gt;&apos; oncli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poap_434 {
            get {
                return ResourceManager.GetString("poap_434", resourceCulture);
            }
        }
    }
}
